### ISSUE TITLE
Link naar publicatie Inholland?

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#27]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/d8d66536ff055a5d84b76f2fded897b3f4d5b52e/content/methods/observations/tips.md?plain=1#L13

Volgens mij mist hier een link naar de publicatie.

**Comment by ShKlinkenberg** [comment]
opgelost
