### ISSUE TITLE
Citaten duidelijker weergeven?

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#40]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/5379ded2e84d8cb28bf41d6a1fa93a9d420be8f1/content/methods/project_product/tips.md?plain=1#L11

Is dit een citaat? Zo ja, is er een manier in Github om het anders weer te geven zodat het meteen duidelijk is dat het om een citaat gaat? Wat ook kan is de tekst plaatsen tussen " " en schuindrukken, met evt. tussen haakjes achter het citaat de functie van de betreffende persoon: (hbo-docent)

**Comment by ShKlinkenberg** [comment]
Je kan aan de > zien dat het een citaat is. Ik moet daar echter een css style voor toevoegen en dat is tot nu to nog niet gelukt.

**Comment by ShKlinkenberg** [comment]
Ik heb blockquotes toegevoegd aan de citaten.
