### ISSUE TITLE
'Definitie' en/of 'Beschrijving'

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#43]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/689a3735a8a1dd98c3d396578ebf283b08b6f8a9/content/large/knowledge/description.Rmd#L2

Bij de verschillende toetsmethoden wordt begonnen met het kopje 'Definitie' en bij de toetsdoelen (kennis, toepassing, fysieke handelingen) met het kopje 'Beschrijving'. Is hier bewust voor een andere term gekozen, of zou er ook  één en dezelfde term kunnen worden gehanteerd?

**Comment by ShKlinkenberg** [comment]
Dat is idd bewust. Bij het toetsdoel beschrijven we wat we daaronder verstaan.
