### ISSUE TITLE
Snippets die niet los gebruikt kunnen worden van andere tekst/snippets

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#45]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/1ec897d098933b56fe4bafe487c2ca6a4b3764f8/content/snippets/knowledge/know_how_itembanks.md?plain=1#L1

In sommige snippets staan zinsdelen die verwijzen naar andere tekst/snippets, waardoor ze niet los te gebruiken zijn. Is het in deze gevallen beter om deze snippets aan te passen, of anders de twee losse snippets met een link met elkaar samenvoegen?

Bijv. in dit geval: 'Een andere manier om fraude te voorkomen'.

**Comment by ShKlinkenberg** [comment]
Dat moeten we idd tekstueel aanpassen.
