### ISSUE TITLE
Vragen in willekeurige volgorde aanbieden

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#49]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/1ec897d098933b56fe4bafe487c2ca6a4b3764f8/docs/1-on-1/knowledge/methods/digital_assessment.Rmd#L12

De volgende tip wordt gegeven, “Indien het gaat om een toets die ook bij andere studenten wordt afgenomen (bijvoorbeeld op een ander moment), bied de vragen dan in willekeurige volgorde aan om het doorgeven van antwoorden te voorkomen.” Maar is het in willekeurige volgorde aanbieden hier wel voldoende voor? Als ze de vraagstelling hebben onthouden, dan maakt de volgorde toch weinig uit? Volgorde gaat volgens mij meer om als studenten gelijktijdig een tentamen maken en bij elkaar af zouden kunnen kijken.

**Comment by ShKlinkenberg** [comment]
Ik geloof dat het idee is dat het lastiger is om de precieze vraag te onthouden dan het nummer van de vraag. Zeker als de antwoord opties ook nog eens random zijn. Of het voldoende is, is zeker de vraag. Wat zou je nog toe willen voegen?

**Comment by EdwinBuijs** [comment]
Helder. Heb het verwerkt in de tekst bij de betreffende geadviseerde toetsvorm en eraan toegevoegd dat de antwoordopties ook in willekeurige volgorde kunnen worden aangeboden.
