### ISSUE TITLE
Formulering tip bij observaties bij kleine groepsgrootte

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#53]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/292456aeae516243a1e8062afb5109fa598ffcab/content/snippets/knowledge/know_methods_questions.md?plain=1#L1

tips voor deze toetsmethode bij Observaties bij groepsgrootte klein: “Het beoordelen van presentaties, projecten of producten kan veel tijd kosten. Daarom lijkt deze vorm wellicht minder voor de hand liggend voor deze schaal. Echter kan het nakijken van deze toetsvormen in een formatieve setting behapbaarder worden gemaakt door de studenten op te delen in groepen en/of gebruik te maken van peer feedback, waarbij studenten elkaars werk beoordelen. Ook kan het praktisch zijn om de studenten hun presentaties op te laten nemen, zodat de beoordelaar deze tijd- en plaatsonafhankelijk kan beoordelen.” --> ik zou deze tip op deze plek anders formuleren zodat het over observaties gaat, want nu is het dezelfde tekst als bij presentaties, projecten of producten.

**Comment by ShKlinkenberg** [comment]
prima
