### ISSUE TITLE
Identiteitskaart

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#61]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/292456aeae516243a1e8062afb5109fa598ffcab/content/snippets/knowledge/know_methods_ID.md?plain=1#L1

De tip “Vraag de student een identiteitskaart of studentenpas te tonen als de beoordelaar onbekend is met de student.” wordt nu maar in het geval van enkele toetsvormen gegeven (bijv. bij presentaties). Dit lijkt me eigenlijk meer een algemene tip dan een tip die gekoppeld is aan een specifieke toetsvorm.

**Comment by ShKlinkenberg** [comment]
eens

**Comment by EdwinBuijs** [comment]
Ik heb geprobeerd om een verwijzing te plaatsen naar de betreffende snippet bij de algemene tips. Het is echter niet gelukt. Op welke manier kan dit worden gedaan? Het gaat om de snippet [content/snippets/knowledge/know_methods_ID.md](https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/158f48a74ccef20f24a9e2c2a3f246b39c34538f/content/snippets/knowledge/know_methods_ID.md)
