### ISSUE TITLE
Peerfeedback

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#62]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/292456aeae516243a1e8062afb5109fa598ffcab/content/snippets/observation/obs_tips_peerfeedback.md?plain=1#L1

De tip dat bij formatieve evaluatie gebruik kan worden gemaakt van peer feedback wordt nu wel als algemene tip genoemd bij fysieke handelingen, maar bijv. niet bij toepassing, hoewel het me daar ook een relevante tip lijkt.

Overweging om bij deze tip ook te verwijzen naar meer informatie over hoe je invulling kunt geven aan peerfeedback?

**Comment by ShKlinkenberg** [comment]
herschrijven

**Comment by EdwinBuijs** [comment]
Ik heb de link naar meer informatie toegevoegd. Nu vraag ik me bij nader inzien echter af waarom deze tip eigenlijk wordt vermeld bij fysieke handelingen, gezien er in dit onderdeel verder niet wordt ingegaan op formatief evalueren.
