### ISSUE TITLE
Toon meer / toon minder

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#63]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/fc8cf848d30b301c4616cd8f7bd4b242178f3fca/docs/methods/portfolio/index.html#L176

De functie 'Toon meer' en 'Toon minder' is nu op sommige pagina's wel actief en op andere niet (bijv. wel bij de informatie over de toetsvormen en bij groepsgrootte gemiddeld, maar niet bij groot en klein). Dit consequent overal wel of niet toepassen. Persoonlijk denk ik dat deze optie niet nodig is omdat het niet om hele lange teksten gaat.

**Comment by ShKlinkenberg** [comment]
laten we zo
