### ISSUE TITLE
Open boek-tentamens

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#65]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/292456aeae516243a1e8062afb5109fa598ffcab/content/small/application/description.html#L14

Open boek-tentamens worden wel genoemd bij de digitale toetsen, maar er wordt niet dieper op ingegaan. Is hier bewust voor gekozen? Of is het wenselijk dat hier nog wel nader op in wordt gegaan?

**Comment by ShKlinkenberg** [comment]
Beter beschrijven / toevoegen bij product tekst. Wat versta je onder een openbreek tentamen. Voornamelijk bij digitaal toetsen
