### ISSUE TITLE
Observaties bij zowel toepassing als fysieke handelingen?

### ISSUE THREAD

**Issue by EdwinBuijs** [Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool#70]
https://github.com/Werkgroep-Toetsen-Op-Afstand/assessment-selection-tool/blob/2f86dbdc13293ed1d92ea805a85cf7297cd28388/docs/1-on-1/application/methods.Rmd#L46

Observaties wordt nu ook als toetsvorm besproken bij toepassingen, maar deze wordt niet genoemd in de beschrijving. En is hier ook geen sprake van overlap met fysieke handelingen? Is een observatie bij toepassing niet per definitie ook een observatie van een fysieke handeling?

**Comment by ShKlinkenberg** [comment]
besproken
